### PR TITLE
Python 3.9 Support

### PR DESCRIPTION
**Pull request by alimcmaster1**
Python 3.9 Support - 3.10 should be soon :)

### CODE REVIEW

**Comment by serhiibuniak-okta** [comment]
@alimcmaster1 Thank you for your contribution. In order to trigger all CI checks I'll need to create our branch and push your commits to that branch. Let me do this.

**Comment by alimcmaster1** [comment]
> @alimcmaster1 Thank you for your contribution. In order to trigger all CI checks I'll need to create our branch and push your commits to that branch. Let me do this.

Thanks have just emailed across the CLA too.

**Comment by alimcmaster1** [comment]
> @alimcmaster1 Thank you for your contribution. In order to trigger all CI checks I'll need to create our branch and push your commits to that branch. Let me do this.

Any update on this @serhiibuniak-okta

**Comment by serhiibuniak-okta** [comment]
@alimcmaster1 Sorry for delay, there were some technical issues. Now we're waiting for a review, I'll ping reviewers. And we will be able to release new sdk version after this https://github.com/okta/okta-sdk-python/pull/241 is merged.

**Review by bretterer — COMMENTED** [review]
I believe this is overridden by #237

**Comment by alimcmaster1** [comment]
> @alimcmaster1 Sorry for delay, there were some technical issues. Now we're waiting for a review, I'll ping reviewers. And we will be able to release new sdk version after this #241 is merged.

Thanks! Great to get this done!

**Pull request merged**
