### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by gabrielsroka**
it seems to be okta.yaml, not .okta.yaml, per https://github.com/okta/okta-sdk-python/blob/master/okta/constants.py#L25

added a hello world and text describing it

removed `here` in links

minor formatting

### CODE REVIEW

**Comment by serhiibuniak-okta** [comment]
Thank you for your contribution, let me check it.

**Review by serhiibuniak-okta — COMMENTED** [review]
Fix for okta.yaml path is correct. But I'm wondering if such configuration works with proxy section where all values set to null:
`okta/config/config_validator.py", line 59, in validate_config
    raise ValueError(f"{newline}Errors:"
ValueError: 
Errors:
Proxy port number must be a number, and between 1 and 65535 (inclusive)`
If I remove proxy section from okta.yaml it works perfectly

**Review by bretterer — APPROVED** [review]
Thanks for the readme changes here! This looks great!

**Comment by bretterer** [comment]
@gabrielsroka we have made another change along with this PR and will handle it in our PR #128 that has your contributions in it as well.

**Pull request closed without merging**
