### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by gabrielsroka**
add logging config info

### CODE REVIEW

**Comment by serhiibuniak-okta** [comment]
@gabrielsroka Thank your for your contribution. Have you checked if logging config in yaml file works correctly?

**Comment by gabrielsroka** [comment]
of course. i wouldn't submit code/docs without testing them first. but i trust you will double-check my work.

i referenced
https://github.com/okta/okta-sdk-python/blob/46184663baccb926dc14ab964dfd9406d375de0a/okta/config/config_setter.py#L110-L112
and
https://github.com/okta/okta-sdk-python/blob/45366dd92307643856d4f6d90e965b5429176ffc/okta/client.py#L154-L158

**Comment by gabrielsroka** [comment]
since the default for enabled is false, it might be better to change the example from true to false.

**Review by serhiibuniak-okta — APPROVED** [review]
Logging config works perfectly, I've checked. Thank you.

**Pull request merged**
