### PR TITLE
Fix __init__ paths per #9

### PR DESCRIPTION
**Pull request by dabdine-r7**

### CODE REVIEW

**Comment by steveYeah** [comment]
@tbelote-okta Any chance you could merge this and push a release? I noticed you were active on here a few hours ago, so thought it would be worth giving you a shout 😄 

This would sort out issues:
https://github.com/okta/oktasdk-python/issues/9
https://github.com/okta/oktasdk-python/issues/7
and maybe https://github.com/okta/oktasdk-python/issues/5 (python 2.7 so not sure)

I'm sure you guys are busy, but it would help us out alot. Thanks!

**Comment by tbelote-okta** [comment]
Sorry for the long delay in responding, a contributor license agreement process is coming soon and we will be reaching out to accept this PR.

**Comment by steveYeah** [comment]
@tbelote-okta Thanks for the update!

**Comment by jmelberg-okta** [comment]
Hi @dabdine-r7! Thanks for your pull request. 

Before we can move forward with reviewing/merging your PR, please take a moment to read and sign a Contributor License Agreement (CLA).

Please visit [developer.okta.com/cla](http://developer.okta.com/cla/) to sign.

Then, reply here (“`Signed`”) so we can proceed. Thanks!

**Comment by StabbyCutyou** [comment]
This appears like it might be fixed now in the master branch? Is this the case? Can we expect pip install to work again?

**Comment by jmelberg-okta** [comment]
@StabbyCutyou: The master branch provides a fix for using this SDK with Python 3.3+.

We will be pushing an update so `pip install okta` will include all recent updates as soon as we can.

**Comment by nicolastrres** [comment]
@jmelberg-okta is there any news on this? Do you know when an update with the fix will be available on pip? The last version available on [pypi](https://pypi.python.org/pypi/okta) is `0.0.3` and it does not include the fix.

**Comment by jmelberg-okta** [comment]
@nicolastrres: We are making a few more updates to this SDK before an official `pypi` release. We apologize for the inconvenience and will publish an update as soon as we can.

**Comment by edpark** [comment]
Hi, now that it's June can we get an update on when this will be patched?

**Comment by jmelberg-okta** [comment]
Fixed with #21.

**Pull request closed without merging**
