### PR TITLE
Implementation of ApplicationClient.get_metadata_for_saml_application

### PR DESCRIPTION
**Pull request by molar-volume**
resolve https://github.com/okta/okta-sdk-python/issues/303
fix https://github.com/okta/okta-sdk-python/issues/305
fix https://github.com/okta/okta-sdk-python/issues/301
resolve https://github.com/okta/okta-sdk-python/issues/302

### CODE REVIEW

**Review by LcTrKiD — APPROVED** [review]

**Comment by molar-volume** [comment]
@LcTrKiD please can you approve again? I had to merge master into this PR.
Thanks

**Review by LcTrKiD — APPROVED** [review]

**Comment by LcTrKiD** [comment]
> @LcTrKiD please can you approve again? I had to merge master into this PR.
> Thanks

I don’t think my reviews are valid because I’m not admin here but anyway your code seems good to me

**Comment by molar-volume** [comment]
@vijetmahabaleshwar-okta

**Comment by bretterer** [comment]
Resolved in 2.9.0.  Thank you

**Pull request closed without merging**
