### PR TITLE
Custom role

### PR DESCRIPTION
**Pull request by junior-expert**
Add support for "CUSTOM" role type

### CODE REVIEW

**Comment by junior-expert** [comment]
If a user has custom role assigned, "list_group_targets_for_role" function would raise as CUSTOM rule is not supported.  this update will fix it.

**Comment by gabrielsroka** [comment]
@junior-expert You might notice that the file you modified is automatically generated. You may need to open an issue in this other repo:
https://github.com/okta/okta-management-openapi-spec

Particularly this file:
https://github.com/okta/okta-management-openapi-spec/blob/master/dist/spec.yaml

**Comment by junior-expert** [comment]
@gabrielsroka thanks for pointing me to the correct direction. I've submitted MR here https://github.com/okta/okta-management-openapi-spec/pull/160

**Comment by bretterer** [comment]
This has been resolved in 2.9.0

**Pull request closed without merging**
