### PR TITLE
Adds support for "get groups for user" API

### PR DESCRIPTION
**Pull request by jacob-salassi**
🌱  Adds support for "get groups for user" API in UsersClient.py

https://developer.okta.com/docs/api/resources/users.html#get-member-groups

### CODE REVIEW

**Comment by jacob-salassi** [comment]
Hey all, any word on this PR? Its a small change and is consistent with the contributor guidelines.

**Comment by leetrout** [comment]
Can we get an update on this PR?

**Comment by jacob-salassi** [comment]
@nbarbettini is there any reason this PR cant be merged?

**Comment by nbarbettini** [comment]
Hey @jacob-salassi, sorry for the lack of response. This project and repo are currently unmaintained. We aren't merging any PRs at the moment.

Are you able to use your forked version of the SDK?

**Comment by nbarbettini** [comment]
Makes sense. Yeah, the Python SDK is currently unsupported. We'd like to build a new version that includes all the recent requests, but don't immediately have plans to do so.

You can vote for Python support here: https://devforum.okta.com/t/python-support-feedback/1778/12
I'd love to understand more about the types of applications you're building with Okta + Python.

**Comment by rickzimbelman-okta** [comment]
Rick Zimbelman, CISSP
Okta Global Services
Sr. Engagement Manager
O: 512-520-5555
C: 512-657-5961
rick.zimbelman@okta.com

[cid:image001.png@01D2E683.AFDA4FB0]

**Comment by bretterer** [comment]
Thank you for your PR and sorry it took so long to get back to it. We have recently released a 1.x version of this SDK which completely updates the structure and build process for our SDK.

I believe our changes no longer require this PR to be included so we are going to close it. If you feel the new version does not resolve the issues you were seeing, prompting this PR, please let us know and we will be happy to re-investigate.

**Pull request closed without merging**
