### PR TITLE
Convert enum element to plain value. OKTA-393048

### PR DESCRIPTION
**Pull request by serhiibuniak-okta**
Related to https://github.com/okta/okta-sdk-python/issues/198

Example of output (used app config from the issue above):

```py
print(type(app), app.sign_on_mode, type(app.sign_on_mode))

<class 'okta.models.application.Application'> BROWSER_PLUGIN <class 'str'>
```

### CODE REVIEW

**Review by bretterer — COMMENTED** [review]
Looks like this may be a breaking change.  If someone is already taking `config["signOnMode"]` and calling `.value` already, what happens?

**Comment by serhiibuniak-okta** [comment]
> Looks like this may be a breaking change. If someone is already taking `config["signOnMode"]` and calling `.value` already, what happens?
Yes, it is a breaking change if someone is already calling `.value`, but config for internal use only and I haven't seen any such usecase. Also, all existing integration tests passed.

**Review by bretterer — CHANGES_REQUESTED** [review]
Current solution is a breaking change.

**Comment by serhiibuniak-okta** [comment]
Closed accordingly to another solution https://github.com/okta/okta-sdk-python/pull/215

**Pull request closed without merging**
