### PR TITLE
Fix find_packages() also finding the tests dir

### PR DESCRIPTION
**Pull request by flying-sheep**
`tests` isn’t a package, but when you make it look like one, `find_packages()` in `setup.py` will find it and accidentally install it globally in `site-packages`.

This should fix that.

### CODE REVIEW

**Comment by serhiibuniak-okta** [comment]
Thank you for this PR, yes now I see the problem now. On the other hand, I think, we should exclude tests from packaging: tests will require a bit more disk space including test requirements and a bit more time to install everything. User can clone repo and run tests at any time. What are your thoughts on it?

**Comment by flying-sheep** [comment]
This PR will achieve exactly that.

**Comment by serhiibuniak-okta** [comment]
I think it would be better to exclude tests from packaging and we won't need to fix failing tests, i.e. change find_packages to the following:
```py
packages=find_packages(exclude=("tests",)),
```
Could you please, confirm it works as expected?

**Comment by flying-sheep** [comment]
Well, I’d be all for doing what @serhiibuniak-okta said quickly, doing a new release without a problematic top-level `tests` package, and then doing what I proposed.

**Comment by serhiibuniak-okta** [comment]
@flying-sheep Thanks, let us make a new release first. I've got your point, according to https://docs.pytest.org/en/stable/goodpractices.html we should make tests a package. But it might require some changes in layout as per https://blog.ionelmc.ro/2014/05/25/python-packaging/#the-structure. Need to think and test everything very thoroughly.

**Comment by flying-sheep** [comment]
> according to docs.pytest.org/en/stable/goodpractices.html we should make tests a package

you misinterpreted that, see [the import mode docs](https://docs.pytest.org/en/stable/pythonpath.html#import-modes):

> `importlib`: new in pytest-6.0, this mode uses importlib to import test modules.
> […]
> makes test modules non-importable by each other.
> […]
> 
> **We intend to make importlib the default in future releases.**

So removing the `__init__.py` makes you future-proof

**Comment by serhiibuniak-okta** [comment]
@flying-sheep Version 1.2.1 is ready, so tests won't mess in site-packages. Meanwhile, I'll investigate the solution with removing __init__.py. Feel free to add anything else you think might be helpful.

**Comment by flying-sheep** [comment]
OK, thank you! It’s your choice of course, I’m happy with the package not being installed top level anymore

**Pull request closed without merging**
