### PR TITLE
Merge third-party contributions

### PR DESCRIPTION
**Pull request by serhiibuniak-okta**
Commits included:
Readme update - https://github.com/okta/okta-sdk-python/pull/181
Fix return value - https://github.com/okta/okta-sdk-python/pull/180, https://github.com/okta/okta-sdk-python/pull/182

### CODE REVIEW

**Comment by bretterer** [comment]
What is the original ticket for these third party contributions?

**Comment by serhiibuniak-okta** [comment]
> What is the original ticket for these third party contributions? And has there been a CLA?

No ticket, no CLA. I'm considering it as an "obvious fix": 1) small readme fix to make consistent examples; 2) return 2 values from given method as it should be (probably, returning 1 value was kind of typo mistake)

**Comment by oleksandr-kaleniuk** [comment]
@bretterer @serhiibuniak-okta the bug with return value is rather critical because it doesn't allow us to use pagination. May I ask you to merge it when you have time?

**Comment by serhiibuniak-okta** [comment]
Hi, @oleksandr-kaleniuk, we'll do it soon, but anyway we need to release a new version of sdk to make this fix accessible. We'll keep you posted.

**Review by bretterer — APPROVED** [review]

**Pull request merged**
