### PR TITLE
Adds basic User Schema support

### PR DESCRIPTION
**Pull request by mchurichi**
Adds Schema client
Adds User Schema model
Adds the ability to create custom user profile properties

### CODE REVIEW

**Comment by videte47** [comment]
what will it take to get this PR merge ?

**Comment by kunzimariano** [comment]
+1 to that.

**Comment by robertjd** [comment]
Thanks everyone for the +1s, we'll review this in an upcoming sprint.

**Comment by bretterer** [comment]
Thank you for your PR and sorry it took so long to get back to it. We have recently released a 1.x version of this SDK which completely updates the structure and build process for our SDK.

I believe our changes no longer require this PR to be included so we are going to close it. If you feel the new version does not resolve the issues you were seeing, prompting this PR, please let us know and we will be happy to re-investigate.

**Pull request closed without merging**
