### PR TITLE
Added method to get all users from an application

### PR DESCRIPTION
**Pull request by PerGon**

### CODE REVIEW

**Comment by danfaizer** [comment]
+1

Tested and worked flawless

**Comment by tbelote-okta** [comment]
Sorry for the long delay in responding, a contributor license agreement process is coming soon and we will be reaching out to accept this PR.

**Comment by jmelberg-okta** [comment]
Hi @PerGon! Thanks for your pull request. 

Before we can move forward with reviewing/merging your PR, please take a moment to read and sign a Contributor License Agreement (CLA).

Please visit [developer.okta.com/cla](http://developer.okta.com/cla/) to sign.

Then, reply here (“`Signed`”) so we can proceed. Thanks!

**Comment by bretterer** [comment]
Thank you for your PR and sorry it took so long to get back to it. We have recently released a 1.x version of this SDK which completely updates the structure and build process for our SDK.

I believe our changes no longer require this PR to be included so we are going to close it. If you feel the new version does not resolve the issues you were seeing, prompting this PR, please let us know and we will be happy to re-investigate.

**Pull request closed without merging**
